GET http://localhost:8080/api/empresa

###

POST http://localhost:8080/api/empresa
content-type: application/json

{
    "corporateName": "Somapay",
    "balance": 50000.00,
    "email": "someemail@some.com"
}

###

POST http://localhost:8080/api/empresa
content-type: application/json

{
    "corporateName": "Some Corporate",
    "balance": 80000.00,
    "email": "somecorporate@some.com"
}

### 

GET http://localhost:8080/api/empresa/1

### 

DELETE  http://localhost:8080/api/empresa/2

### 

PUT  http://localhost:8080/api/empresa/1
content-type: application/json

{
    "corporateName": "Somapay Corporate"
}

### 

GET http://localhost:8080/api/empresa/1/obterSaldo