GET http://localhost:8080/api/empresa
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag

###

POST http://localhost:8080/api/empresa
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag

{
    "corporateName": "Somapay",
    "balance": 50000.00,
    "email": "someemail@some.com"
}

###

POST http://localhost:8080/api/empresa
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag

{
    "corporateName": "Some Corporate",
    "balance": 80000.00,
    "email": "somecorporate@some.com"
}

### 

GET http://localhost:8080/api/empresa/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag


### 

DELETE  http://localhost:8080/api/empresa/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag

### 

PUT  http://localhost:8080/api/empresa/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag

{
    "corporateName": "Somapay Corporate"
}

### 

GET http://localhost:8080/api/empresa/1/obterSaldo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTg5ODc0fQ.zfpXUERRiLbc2_kWWkNrwuMiKQt8wFFlgcJJmJluy0NSXCSuN1LAszkQRzL5peddLaQQoRVFrloOgd4bOo8-Ag