GET http://localhost:8080/api/funcionario
content-type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTcyODUzfQ.jShquBqgBeYw55GYxEM1FRllXK0y-__qjqYSnBClxwHRx_-k7oq6iZCqTaCiB1GV5VyXvcZdzzBztRLD-lrTuQ

###

POST http://localhost:8080/api/funcionario
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTcyODUzfQ.jShquBqgBeYw55GYxEM1FRllXK0y-__qjqYSnBClxwHRx_-k7oq6iZCqTaCiB1GV5VyXvcZdzzBztRLD-lrTuQ

{
    "name": "Eder Nilson",
    "salary": 1000.00,
    "balance": 1000.00,
    "companyId": 1
}

### 

POST http://localhost:8080/api/funcionario
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTcyODUzfQ.jShquBqgBeYw55GYxEM1FRllXK0y-__qjqYSnBClxwHRx_-k7oq6iZCqTaCiB1GV5VyXvcZdzzBztRLD-lrTuQ

{
    "name": "William",
    "salary": 4000.00,
    "balance": 1000.00,
    "companyId": 1
}

### 

GET http://localhost:8080/api/funcionario/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTcyODUzfQ.jShquBqgBeYw55GYxEM1FRllXK0y-__qjqYSnBClxwHRx_-k7oq6iZCqTaCiB1GV5VyXvcZdzzBztRLD-lrTuQ

### 

DELETE  http://localhost:8080/api/funcionario/1

### 

PUT  http://localhost:8080/api/funcionario/2
content-type: application/json

{
    "name": "Eder Nilson",
    "salary": 8000.00
}

### 

GET http://localhost:8080/api/funcionario/2/obterSaldo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjIzMTcyODUzfQ.jShquBqgBeYw55GYxEM1FRllXK0y-__qjqYSnBClxwHRx_-k7oq6iZCqTaCiB1GV5VyXvcZdzzBztRLD-lrTuQ
