GET http://localhost:8080/api/funcionario

###

POST http://localhost:8080/api/funcionario
content-type: application/json

{
    "name": "Eder Nilson",
    "salary": 1000.00,
    "balance": 1000.00,
    "companyId": 1
}

### 

POST http://localhost:8080/api/funcionario
content-type: application/json

{
    "name": "William",
    "salary": 4000.00,
    "balance": 1000.00,
    "companyId": 1
}

### 

GET http://localhost:8080/api/funcionario/1

### 

DELETE  http://localhost:8080/api/funcionario/1

### 

PUT  http://localhost:8080/api/funcionario/2
content-type: application/json

{
    "name": "Eder Nilson",
    "salary": 8000.00
}

### 

GET http://localhost:8080/api/funcionario/2/obterSaldo